# Deployment do PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.13
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: POSTGRES_USER
              value: "review"
            - name: POSTGRES_PASSWORD
              value: "Passw0rd2023!"
            - name: POSTGRES_DB
              value: "review"

---
# Serviço do PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
# Deployment do Review de Filmes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review
          image: palmeirasrodrigo/review-jornada:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgre;Database=review;Username=review;Password=Passw0rd2023!"

---
# Serviço do Review de Filmes
apiVersion: v1
kind: Service
metadata:
  name: review
spec:
  selector:
    app: review
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080





